---
# strongswan tasks/Debian.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Install strongSwan package (Debian)
  apt:
    name: "{{ strongswan_package }}"
    state: "present"
    update_cache: true
  notify:
    - start-strongswan

- name: Enable strongSwan Service
  service:
    name: "{{ strongswan_service }}"
    enabled: true
