---
# strongswan handlers/main.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: start-strongswan
  service:
    name: "{{ strongswan_service }}"
    state: started

- name: restart-ipsec
  command: ipsec restart
