---
# strongswan molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2020 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all
  vars:
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify package is installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - strongswan

    - name: Verify ipsec command is functional
      command: ipsec version
      register: ipsec_version
      changed_when: false
      failed_when: '"strongSwan" not in ipsec_version.stdout'
